#!/usr/bin/env python3

import sys
import gi
sys.path.append(../)
gi.require_version('Gst', '1.0')
from gi.repository import Glib, Gst
from common.bus_call import bus_call
from common.is_aarch_64 import is_aarch64



